[package]
name = "rust-translator"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[dependencies]
tokio = { version = "1.20", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "blocking", "socks"] }
serde_json = "1.0"
colored = "2.0"
chrono = "0.4.22"
cli-clipboard = "0.2"
clap = { version = "3.2", features = ["derive"] }
